### ISSUE TITLE
Issue while running muicache dissect plugin

### ISSUE THREAD

**Issue by M1ra1B0T** [dfir-dd/kirby#1]
I do get the following error message when running the quicktimeline script:
```
Traceback (most recent call last):
  File "/home/vagrant/Tools/quicktimeline/quicktimeline.py", line 17, in <module>
    main()
  File "/home/vagrant/Tools/quicktimeline/quicktimeline.py", line 12, in main
    analyzer.invoke_plugins()
  File "/home/vagrant/Tools/quicktimeline/utils/HostAnalyzer.py", line 73, in invoke_plugins
    self.invoke_plugin(plugin)
  File "/home/vagrant/Tools/quicktimeline/utils/HostAnalyzer.py", line 87, in invoke_plugin
    self.write_csv(filename, records)
  File "/home/vagrant/Tools/quicktimeline/utils/HostAnalyzer.py", line 99, in write_csv
    for entry in records:
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/plugins/os/windows/regf/muicache.py", line 63, in muicache
    yield from self._get_records(item)
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/plugins/os/windows/regf/muicache.py", line 68, in _get_records
    for index, entry in enumerate(key.values()):
                                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/helpers/regutil.py", line 667, in values
    return [RegfValue(self.hive, v) for v in self.key.values()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/helpers/regutil.py", line 667, in <listcomp>
    return [RegfValue(self.hive, v) for v in self.key.values()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/regf/regf.py", line 234, in values
    for i in values_list:
  File "/usr/local/lib/python3.11/dist-packages/dissect/regf/regf.py", line 346, in __iter__
    yield KeyValue(self.hive, self.hive.read_cell_data(entry))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/regf/regf.py", line 70, in read_cell_data
    size = c_regf.int32(self.fh)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/cstruct/types/base.py", line 24, in __call__
    return self.read(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/cstruct/types/base.py", line 73, in read
    return self._read(obj)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/cstruct/types/packedtype.py", line 20, in _read
    return self._read_array(stream, 1, context)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/cstruct/types/packedtype.py", line 28, in _read_array
    raise EOFError(f"Read {len(data)} bytes, but expected {length}")
EOFError: Read 0 bytes, but expected 4
```
It seems that running the muicache plugin fails. 
I did run the script on a triage zip archive from velociraptor.

**Comment by M1ra1B0T** [comment]
Additionally I found out, that the output of the muicache plugin differs between different host os.
I ran the script on kali linux and got the above mentioned errors.
I also ran the script on Ubuntu and did not receive this error, however, the resulting muicache output had fewer lines and information, than the output from the script ran on kali. I ran both scripts on the same triage data.

**Comment by M1ra1B0T** [comment]
This is not an issue of the script, but coming from the dissect plugin itself. Needs to be addressed in the dissect project.
